console.log('dziala');
// fetch("https://api.github.com/users/kariminK").then(response=>response.json()).then(data=>console.log(data))

// login: 'KariminK', id: 103779342, node_id: 'U_kgDOBi-MDg', avatar_url: 'https://avatars.githubusercontent.com/u/103779342?v=4', gravatar_id: '', …}
// avatar_url
// : 
// "https://avatars.githubusercontent.com/u/103779342?v=4"
// bio
// : 
// "Hello! I'm Karimin and I am doing some basic frontend projects "
// blog
// : 
// ""
// company
// : 
// null
// created_at
// : 
// "2022-04-15T19:34:13Z"
// email
// : 
// null
// events_url
// : 
// "https://api.github.com/users/KariminK/events{/privacy}"
// followers
// : 
// 0
// followers_url
// : 
// "https://api.github.com/users/KariminK/followers"
// following
// : 
// 0
// following_url
// : 
// "https://api.github.com/users/KariminK/following{/other_user}"
// gists_url
// : 
// "https://api.github.com/users/KariminK/gists{/gist_id}"
// gravatar_id
// : 
// ""
// hireable
// : 
// null
// html_url
// : 
// "https://github.com/KariminK"
// id
// : 
// 103779342
// location
// : 
// null
// login
// : 
// "KariminK"
// name
// : 
// "KariminK"
// node_id
// : 
// "U_kgDOBi-MDg"
// organizations_url
// : 
// "https://api.github.com/users/KariminK/orgs"
// public_gists
// : 
// 0
// public_repos
// : 
// 6
// received_events_url
// : 
// "https://api.github.com/users/KariminK/received_events"
// repos_url
// : 
// "https://api.github.com/users/KariminK/repos"
// site_admin
// : 
// false
// starred_url
// : 
// "https://api.github.com/users/KariminK/starred{/owner}{/repo}"
// subscriptions_url
// : 
// "https://api.github.com/users/KariminK/subscriptions"
// twitter_username
// : 
// null
// type
// : 
// "User"
// updated_at
// : 
// "2023-02-24T10:03:06Z"
// url
// : 
// "https://api.github.com/users/KariminK"